config/routes.rb
TempleRails::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  match '/contact/new' => 'contact#new', :as => :new_contact, :via => :get
  match '/contact' => 'contact#new', :as => :contact, :via => :get
  match '/contact' => 'contact#create', :as => :contact, :via => :post
  match '/prayer/new' => 'prayer#new', :as => :new_prayer, :via => :get
  match '/prayer' => 'prayer#new', :as => :prayer, :via => :get
  match '/prayer' => 'prayer#create', :as => :prayer, :via => :post
  match '/about' => 'about#index', :as => :about
  match '/calendar' => 'calendar#index', :as => :calendar
  match '/' => 'home#index', :as => :home

  resources :sermons
  resources :pages
  resources :announcements

  match 'children/:id' => 'pages#show', :as => :page
  match 'events/:id' => 'pages#show', :as => :events
  match '/' => 'home#index'
  match '/:id' => 'pages#show', :as => :page
  match '/:controller(/:action(/:id))'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  after_create { |admin| admin.send_reset_password_instructions }
  def password_required?
    new_record? ? false : super
  end
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :what, :ann_date, :ann_time, :location, :details, :published
  validates_presence_of :what, :ann_date, :ann_time, :location, :details
  has_friendly_id :what, :use_slug => true

  scope :active, where("published = 1 and ann_date >= curdate()").order("ann_date ASC, ann_time desc")
  scope :inactive, where("published != 1")
  scope :expired, where("published = 1 and ann_date <= curdate()").order("ann_date ASC, ann_time desc")

  def display_ann_date
    ann_date.strftime('%m-%d-%y')
  end

  def display_ann_time
    ann_time.strftime('%l:%M%p')
  end

  def display_date_and_time
    self.display_ann_date + " " + self.display_ann_time
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base

  # === List of columns ===
  #   id                : integer 
  #   data_file_name    : string 
  #   data_content_type : string 
  #   data_file_size    : integer 
  #   assetable_id      : integer 
  #   assetable_type    : string 
  #   type              : string 
  #   locale            : integer 
  #   user_id           : integer 
  #   created_at        : datetime 
  #   updated_at        : datetime 
  # =======================

  
  belongs_to :user
  belongs_to :assetable, :polymorphic => true
  
  def url(*args)
    data.url(*args)
  end
  alias :public_filename :url
  
  def filename
    data_file_name
  end
  
  def content_type
    data_content_type
  end
  
  def size
    data_file_size
  end
  
  def path
    data.path
  end
  
  def styles
    data.styles
  end
  
  def format_created_at
    I18n.l(self.created_at, :format=>"%d.%m.%Y %H:%M")
  end
  
  def to_xml(options = {})
    xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])

    xml.tag!(self.type.to_s.downcase) do
      xml.filename{ xml.cdata!(self.filename) }
      xml.size self.size
      xml.path{ xml.cdata!(self.url) }
      
      xml.styles do
        self.styles.each do |style|
          xml.tag!(style.first, self.url(style.first))
        end
      end unless self.styles.empty?
    end
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pages
end

app/models/happening.rb
class Happening < ActiveRecord::Base
  attr_accessible :name, :image, :details
  mount_uploader :image, ImageUploader
end

app/models/happenings.rb
class Happenings < ActiveRecord::Base
  attr_accessible :name, :image, :details
  mount_uploader :image, ImageUploader
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_friendly_id :title, :use_slug => true
  belongs_to :category

end

app/models/picture.rb
class Picture < Asset

  # === List of columns ===
  #   id                : integer 
  #   data_file_name    : string 
  #   data_content_type : string 
  #   data_file_size    : integer 
  #   assetable_id      : integer 
  #   assetable_type    : string 
  #   type              : string 
  #   locale            : integer 
  #   user_id           : integer 
  #   created_at        : datetime 
  #   updated_at        : datetime 
  # =======================

  
  has_attached_file :data,
                    :url  => "/system/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/system/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '575>', :thumb => '100x100' }
	
	validates_attachment_size :data, :less_than=>2.megabytes
	
	def url_content
	  url(:content)
	end
	
	def url_thumb
	  url(:thumb)
	end
	
	def to_json(options = {})
	  options[:methods] ||= []
	  options[:methods] << :url_content
	  options[:methods] << :url_thumb
	  super options
  end
end

app/models/prayer_handler.rb
class PrayerHandler
  include ActiveModel::Validations

  validates_presence_of :name, :email, :subject, :body
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  
  attr_accessor :name, :subject, :email, :body, :add_to_bulletin

  def initialize(attributes = {})
    attributes.each do |key, value|
      self.send("#{key}=", value)
    end
    @attributes = attributes
  end

  def read_attribute_for_validation(key)
    @attributes[key]
  end

  def to_key
  end

  def save
    if self.valid?
      PrayerMailer.prayer_notification(self).deliver
      return true
    end
    return false
  end
end

app/models/promo.rb
class Promo < ActiveRecord::Base
  attr_accessible :name, :image, :details
  mount_uploader :image, ImageUploader
end

app/models/sermon.rb
class Sermon < ActiveRecord::Base
  has_friendly_id :title, :use_slug => true

  def display_date
    date.strftime('%m-%d-%y')
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/pages/_form.html.erb
  <%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" %> 
  <%= semantic_form_for [:admin, @page], :multipart => true do |f| %>
    <%= f.inputs do %>
    <%= f.input :title, :label => "Title" %>
    <%= f.input :section, :label => "Section" %>
    <%= f.input :published, :label => "Published" %>
    <%= f.input :body, :as => :ckeditor %>
    <% end %>
    <%= f.buttons %>
  <% end %>  

app/views/shared/_accordion.html.erb
    <div id="accordion"> 
 
    <h2 class="current">First pane</h2> 
    <div class="pane" style="display:block">... pane content ...</div> 
 
    <h2>Second pane</h2> 
    <div class="pane">... pane content ...</div> 
 
    <h2>Third pane</h2> 
    <div class="pane">... pane content ...</div> 
 
    </div>

    <script type='text/javascript'>
    $("#accordion").tabs("#accordion div.pane", {tabs: 'h2', effect: 'slide', initialIndex: null});
    </script>

app/views/shared/_analytics.html.erb
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-5248159-26");
pageTracker._trackPageview();
} catch(err) {}</script>

app/views/shared/_nav.html.erb
<!-- end #header_wrap -->
<div id="nav_main_wrap">
  <div id="nav_main">
  <%= navigation([
    :home,    'Home',
    :sermons, 'Sermons',
    :calendar , 'Calendar',
    :prayer, 'Prayer',
    :about, 'About',
    :contact, 'Contact Us',
  ], :hover_text => true) %>

  <!--<ol>
  <li class="current"><a href="/home.html">Home</a></li>
  <li><a href="#">About Us</a></li>
  <li><a href="#">Adult Ministries</a></li>
  <li><a href="#">Youth</a></li>
  <li><a href="#">Children's Ministries</a></li>
  <li><a href="#">Sermons</a></li>
  <li><a href="#">Prayer</a></li>
  <li><a href="#">Calendar</a></li>
  <li><a href="#">Contact</a></li>
  </ol>-->
  <span class="clear">&nbsp;</span>
  </div>
</div>
<!-- end #nav_main_wrap -->
<!--
<div id="nav_sub_wrap"><div id="nav_sub"><ul><li><a href="/about-us/visiting-stonebriar.html"  class="first">Visiting Stonebriar?</a></li><li><a href="/worship/sermons.html"  >Sermons</a></li><li><a href="/worship/hispanic-services.html"  >Hispanic Services</a></li><li><a href="/worship/wednesday-nights.html"  >Wednesday Nights</a></li><li><a href="/worship/choirs.html"  >Choirs</a></li><li><a href="/worship/orchestra.html"  >Orchestra</a></li><li><a href="/worship/special-events.html"  >Special Events</a></li></ul><span class="clear">&nbsp;</span></div></div>

 end #nav_sub_wrap -->

app/views/shared/_sidebar.html.erb
    <!-- sidebar -->
    <div class="grid_4 alpha omega" id="sidebar">
        <div class="sidebox">
          <h4>Wednesday, <%= next_wednesday(1) %></h4>
            <ul>
              <li><b>5:30pm - 6:15pm</b> <br>Fellowship Meal
                <%= @wed_night_meal ? '(' + @wed_night_meal.name + ')' : nil %>
              </li>
              <li><br><b>6:20pm - 7:30pm</b> <br>Adult Study, Youth Alter Call, Children Music &amp; Missions</li>
            </ul>
            <h4>Sunday, <%= next_sunday(1) %></h4>
            <ul>
              <li><b>9:15 am</b> - Bible Study</li>
              <li><b>8am &amp; 10:30 am</b> - Morning Worship</li>
              <li><b>5:30 pm</b> - Discipleship</li>
            </ul>
        </div>


    <% if @announcements %>
    <div class="grid_4 omega content_box" id="col-2">
    <h3>Announcements</h3>
    <ul>
    <% @announcements.each do |a| %>
      <!--<li><b><%=h a.display_date_and_time %></b> - <%= link_to a.what, a %></li>-->
      <li><b><%=h a.display_date_and_time %></b> - <%= a.what %></li>
      <!--<li style="padding: 5px 0 5px 0;">
        <h5><%= a.what %></h5>
        <b><%=h a.display_date_and_time %></b>
        <br>
      </li>-->
      <% end %>
    </ul>
    <%= link_to 'View All Announcements', announcements_path %>
    </div>
  <% end %>

    <% if @happening %>
      <div class="grid_4 omega content_box" id="col-2">
        <h3>Temple Happenings</h3>
        <div>
          <%= @happening.details.html_safe %>
        </div>
        <br>
        <%= link_to 'Download Happenings' + @happening.name, @happening.image.url, :class => 'red_button' %>
      </div>
    <% end %>


    <% if false %>
    <!--
    <% upcoming_events.each do |event| %>
    <div class="event-item">
        <a href="#"><%= event[:title] %></a>
        
        <p><strong>Date:</strong>
        <%= event[:start] %><br />
        <%= event[:end] %>
        </p>

    </div>
    <% end %>
    -->
    <% end %>
    <!--
    <ul>
        <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
        <li>Aliquam tincidunt mauris eu risus.</li>
        <li>Vestibulum auctor dapibus neque.</li>
    </ul>
    <ul>
        <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
        <li>Aliquam tincidunt mauris eu risus.</li>
        <li>Vestibulum auctor dapibus neque.</li>
    </ul>
    -->
    </div>

app/views/shared/_simple_nav.html.erb
<!-- end #header_wrap -->
<div id="nav_main_wrap">
  <div id="nav_main">
    <%= render_navigation(:level => 1) %>
  <span class="clear">&nbsp;</span>
  </div>
</div>
<!-- end #nav_main_wrap -->

<!--
<div id="nav_sub_wrap">
    <div id="nav_sub">
    <%= render_navigation(:level => 2) %>
    <span class="clear">&nbsp;</span>
    </div>
</div>


<div id="nav_sub_wrap"><div id="nav_sub"><ul><li><a href="/about-us/visiting-stonebriar.html"  class="first">Visiting Stonebriar?</a></li><li><a href="/worship/sermons.html"  >Sermons</a></li><li><a href="/worship/hispanic-services.html"  >Hispanic Services</a></li><li><a href="/worship/wednesday-nights.html"  >Wednesday Nights</a></li><li><a href="/worship/choirs.html"  >Choirs</a></li><li><a href="/worship/orchestra.html"  >Orchestra</a></li><li><a href="/worship/special-events.html"  >Special Events</a></li></ul><span class="clear">&nbsp;</span></div></div>

 end #nav_sub_wrap -->