config/routes.rb
TempleRails::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  match '/contact/new' => 'contact#new', :as => :new_contact, :via => :get
  match '/contact' => 'contact#new', :as => :contact, :via => :get
  match '/contact' => 'contact#create', :as => :contact, :via => :post
  match '/prayer/new' => 'prayer#new', :as => :new_prayer, :via => :get
  match '/prayer' => 'prayer#new', :as => :prayer, :via => :get
  match '/prayer' => 'prayer#create', :as => :prayer, :via => :post
  match '/about' => 'about#index', :as => :about
  match '/calendar' => 'calendar#index', :as => :calendar
  match '/' => 'home#index', :as => :home

  resources :sermons
  resources :pages
  resources :announcements

  match 'children/:id' => 'pages#show', :as => :page
  match 'events/:id' => 'pages#show', :as => :events
  match '/' => 'home#index'
  match '/:id' => 'pages#show', :as => :page
  match '/:controller(/:action(/:id))'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  after_create { |admin| admin.send_reset_password_instructions }
  def password_required?
    new_record? ? false : super
  end
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :what, :ann_date, :ann_time, :location, :details, :published
  validates_presence_of :what, :ann_date, :ann_time, :location, :details
  has_friendly_id :what, :use_slug => true

  scope :active, where("published = 1 and ann_date >= curdate()").order("ann_date ASC, ann_time desc")
  scope :inactive, where("published != 1")
  scope :expired, where("published = 1 and ann_date <= curdate()").order("ann_date ASC, ann_time desc")

  def display_ann_date
    ann_date.strftime('%m-%d-%y')
  end

  def display_ann_time
    ann_time.strftime('%l:%M%p')
  end

  def display_date_and_time
    self.display_ann_date + " " + self.display_ann_time
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base

  # === List of columns ===
  #   id                : integer 
  #   data_file_name    : string 
  #   data_content_type : string 
  #   data_file_size    : integer 
  #   assetable_id      : integer 
  #   assetable_type    : string 
  #   type              : string 
  #   locale            : integer 
  #   user_id           : integer 
  #   created_at        : datetime 
  #   updated_at        : datetime 
  # =======================

  
  belongs_to :user
  belongs_to :assetable, :polymorphic => true
  
  def url(*args)
    data.url(*args)
  end
  alias :public_filename :url
  
  def filename
    data_file_name
  end
  
  def content_type
    data_content_type
  end
  
  def size
    data_file_size
  end
  
  def path
    data.path
  end
  
  def styles
    data.styles
  end
  
  def format_created_at
    I18n.l(self.created_at, :format=>"%d.%m.%Y %H:%M")
  end
  
  def to_xml(options = {})
    xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])

    xml.tag!(self.type.to_s.downcase) do
      xml.filename{ xml.cdata!(self.filename) }
      xml.size self.size
      xml.path{ xml.cdata!(self.url) }
      
      xml.styles do
        self.styles.each do |style|
          xml.tag!(style.first, self.url(style.first))
        end
      end unless self.styles.empty?
    end
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pages
end

app/models/happening.rb
class Happening < ActiveRecord::Base
  attr_accessible :name, :image, :details
  mount_uploader :image, ImageUploader
end

app/models/happenings.rb
class Happenings < ActiveRecord::Base
  attr_accessible :name, :image, :details
  mount_uploader :image, ImageUploader
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_friendly_id :title, :use_slug => true
  belongs_to :category

end

app/models/picture.rb
class Picture < Asset

  # === List of columns ===
  #   id                : integer 
  #   data_file_name    : string 
  #   data_content_type : string 
  #   data_file_size    : integer 
  #   assetable_id      : integer 
  #   assetable_type    : string 
  #   type              : string 
  #   locale            : integer 
  #   user_id           : integer 
  #   created_at        : datetime 
  #   updated_at        : datetime 
  # =======================

  
  has_attached_file :data,
                    :url  => "/system/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/system/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '575>', :thumb => '100x100' }
	
	validates_attachment_size :data, :less_than=>2.megabytes
	
	def url_content
	  url(:content)
	end
	
	def url_thumb
	  url(:thumb)
	end
	
	def to_json(options = {})
	  options[:methods] ||= []
	  options[:methods] << :url_content
	  options[:methods] << :url_thumb
	  super options
  end
end

app/models/prayer_handler.rb
class PrayerHandler
  include ActiveModel::Validations

  validates_presence_of :name, :email, :subject, :body
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  
  attr_accessor :name, :subject, :email, :body, :add_to_bulletin

  def initialize(attributes = {})
    attributes.each do |key, value|
      self.send("#{key}=", value)
    end
    @attributes = attributes
  end

  def read_attribute_for_validation(key)
    @attributes[key]
  end

  def to_key
  end

  def save
    if self.valid?
      PrayerMailer.prayer_notification(self).deliver
      return true
    end
    return false
  end
end

app/models/promo.rb
class Promo < ActiveRecord::Base
  attr_accessible :name, :image, :details
  mount_uploader :image, ImageUploader
end

app/models/sermon.rb
class Sermon < ActiveRecord::Base
  has_friendly_id :title, :use_slug => true

  def display_date
    date.strftime('%m-%d-%y')
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/models/wed_night_meal.rb
class WedNightMeal < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  current_tab :home
  def index
    @next_wednesday = view_context.next_wednesday.to_s
    @show_sidebar = 1
    @sermons = Sermon.all :conditions => { :published => 1 }, :order => "date DESC", :limit => 5
    @announcements = Announcement.where("published = 1 and ann_date >= curdate()")
                                 .order("ann_date ASC, ann_time desc")
                                 .limit(10)
    @wed_night_meal = WedNightMeal.where("date <= ?", @next_wednesday).order("date desc").first
    @happening = Happening.order("updated_at desc").first
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<!-- "previous slide" button 
<a class="backward">prev</a> -->

<!-- container for the slides -->
<div class="images">

  <!-- first slide 
  <div style="display:hide;width: 90%;">
    <h2>Trunk or Treat</h2>
    <h4>Oct 30, 2011 - 5PM-7PM</h4>
    <h5>Perfect for kids of all ages! Trick or Treat in the Temple parking lot! Adults decorate trunks and hand out candy!</h5>
    <br clear="all"/>
  </div>-->

   <div style="width: 90%;">
    <h3>Kid's Quest 2012</h3>
    <h4>Summer Care Program</h4>
    <h5>June 4th - July 27th, $325 + $25 reg fee, 7AM-5PM, Kindergarten - 5th Grade</h5>
    <h5><a class="red_button" style="width:200px" href="/children/kids-quest-2012">More Information</a></h5>

  </div>


	<!--<div style="width: 100%">

    <h3>Mother's Day Out at Temple</h3>
    <img src="/images/promos/mdo_learning_garden.png" alt="Mother's Day Out - Learning Garden" style="float:right;" />
    <h4>"The Learning Garden"</h4>
    <h5>Tuesday &amp; Thursdays 9:00am - 2:00pm</h5>
    <h5>$30 Registration fee.  $15 per day.</h5>
    <h6>Contact Becky Jenkins at 330-3707 or <a href="mailto:becky@templetoday.com?subject=MDO%20at%20Temple">becky@templetoday.com</a> for more info.</h6>

  </div> -->

	<div style="width: 100%">

    <img src="/images/promos/TempleBaptist_MDO_rev_small.gif" alt="Mother's Day Out" style="float:left;margin-right: 50px;" />
    <h2>Mother's Day Out</h2>
    <h5>Tuesday &amp; Thursdays 9:00am - 2:00pm</h5>
    <h5>$30 Registration fee.  $15 per day.</h5>
    <h6>Contact Becky Jenkins at 330-3707 or <a href="mailto:becky@templetoday.com?subject=MDO%20at%20Temple">becky@templetoday.com</a> for more info.    <a href="/forms/mdoregistrationform_2012.pdf">Download Registration Form</a></h6>
    <br clear="all"/>

  </div>

</div>

<!-- "next slide" button 
<a class="forward">next</a><p> -->

<!-- the tabs -->
<div class="tabs">
	<a href="#"></a>
	<a href="#"></a>
</div>

<!--
<div style="clear:both;margin:30px 0;text-align:center;padding-right:40px">

<button onClick='$("div.tabs").tabs().play();'>Play</button>
<button onClick='$("div.tabs").tabs().stop();'>Stop</button>
</div>-->

    <script type='text/javascript'>
      $(function() {
        //hide all divs first
        $(".images > div").hide();
        $("div.tabs").tabs(".images > div", {
            effect: 'fade',
            fadeOutSpeed: "slow",
            rotate: true
        }).slideshow({autoplay: true, interval: 15000});
    });
    </script>

    <div class="clear"></div>
    <div class="clear"></div>
<!--
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>

    <div class="grid_4 alpha content_box" id="col-1">
    <h3>Last Week's Sermon</h3>
    <h4>The Lord's Supper</h4>
-->
    <!-- http://media.templetoday.com/onlinesermons/09-13-09_sermon.flv -->

<!--
		<a  
			 href="http://media.templetoday.com/onlinesermons/09-13-09_sermon.flv",
			 style="display:block;width:100%;height:300px;"  
			 id="player"> 
		</a> 
        <script type='text/javascript'>
			flowplayer("player", "/flowplayer-3.1.3.swf", { 
                        clip: { 
                            autoPlay: false,  
                            autoBuffering: false
                        } 
                    });
        </script>
    <p>Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.</p>
    </div>

    <div class="grid_4 omega content_box" id="col-2">
    <h3>Recent Activities</h3>
    <h4>Donec non enim in turpis pulvinar facilisis.</h4>
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
    </div>


    <div class="grid_4 alpha content_box" id="col-1">
    <h3>Kid's Quest 2010</h3>
    <h4>Summer Care Program</h4>
    <h5>June 7th - July 30th, 7AM-5PM<br>Kindergarten - 5th Grade</h5>
    <h5><a class="red_button" style="width:200px" href="/children/kids-quest-2010">More Information</a></h5>
  </div>
  -->

    <!--<div class="grid_4 alpha content_box" id="col-1">
    <h3>Temple VBS 2011</h3>
    <h4>July 10-15, 2011</h4>
    <h5>Sunday - Friday - 6:15 PM to 9 PM</h5>
    <h5><a class="red_button" style="width:200px;float:left;" href="http://vbs.templetoday.com" target="_blank">More information</a></h5>
  </div> -->

    <div class="grid_4 alpha content_box" id="col-2">
    <h3>Children's Ministries</h3>
    <h4>Mother's Day Out</h4>
    <h5>Tuesday &amp; Thursdays 9:00am - 2:00pm</h5>
    <h5>$30 Registration fee.  $15 per day.</h5>
    <h6>Contact Becky Jenkins at 330-3707 or <a href="mailto:becky@templetoday.com?subject=MDO%20at%20Temple">becky@templetoday.com</a> for more info.    <a href="/forms/mdoregistrationform_2012.pdf">Download Registration Form</a></h6>
  </div>

    <div class="grid_4 omega content_box" id="col-3">
    <h3>Sermons</h3>
    <ul>
    <% @sermons.each do |sermon| %>
    <li><b><%=h sermon.date %></b> - <%= link_to sermon.title, sermon %></li>
    <% end %>
    </ul>
    <%= link_to 'View All Sermons', sermons_path %>
    </div>

    <div class="grid_8 alpha content_box" id="col-4">
    <h3>About Us</h3>
    <h6>Temple Baptist Church is a fellowship of caring believers who have joined together
under the Lordship of Jesus Christ and the Leadership of the Holy Spirit to... <a href="/about">Read more</a></h6>
    </div>

    <br clear="all" />
<!--
    <div class="grid_4 omega content_box" id="col-4">
    <h3>Discipleship Classes</h3>
    <h4>Join us Sunday evenings as we look more closely at God's word.</h4>
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
    </div>
-->
<!--
    <div class="grid_4 alpha content_box" id="col-3">
    <h3>Calendar</h3>
    <h4></h4>
    <ul>
        <li>Pellentesque habitant</li>
        <li>Pellentesque habitant</li>
        <li>Pellentesque habitant</li>
        <li>Pellentesque habitant</li>
        <li>Pellentesque habitant</li>
    </ul>
    </div>
-->